# Generated by Django 3.2.25 on 2025-06-03 02:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('manage_hospital', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Requested', max_length=20)),
                ('main_reason', models.TextField()),
                ('priority', models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent care', 'Urgent care'), ('Routine', 'Routine')], max_length=20)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_patient', to='patients.patient')),
                ('receiving_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='manage_hospital.doctor')),
                ('receiving_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referrals', to='accounts.facility')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='manage_hospital.doctor')),
                ('referring_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_referrals', to='accounts.facility')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
