# Generated by Django 3.2.25 on 2025-06-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('urgent_care', 'Urgent Care Center'), ('long_term_care', 'Long-Term Care Facility'), ('specialty_center', 'Specialty Center')], max_length=50)),
                ('facility_level', models.CharField(choices=[('primary', 'Primary Care'), ('secondary', 'Secondary Care'), ('tertiary', 'Tertiary Care'), ('quaternary', 'Quaternary Care'), ('emergency', 'Emergency Care')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('kigali', 'Kigali City'), ('northern', 'Northern Province'), ('southern', 'Southern Province'), ('eastern', 'Eastern Province'), ('western', 'Western Province')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('admin_first_name', models.CharField(default='Hospital', max_length=100)),
                ('admin_last_name', models.CharField(default='Hospital', max_length=100)),
                ('admin_position', models.CharField(default='Administrator', max_length=100)),
                ('admin_email', models.EmailField(default='admin@example.com', max_length=254, unique=True)),
                ('admin_phone', models.CharField(default='+250700000000', max_length=20, unique=True)),
                ('admin_password', models.CharField(default='changeme', max_length=255)),
                ('is_approved', models.CharField(default='Pending', max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('plain_password', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('hospital', 'Hospital'), ('admin', 'Admin')], default='admin', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
