# Generated by Django 3.2.25 on 2025-06-03 02:24

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('current_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+2507[89]\\d{7}$', message="Phone number must be a Rwandan number starting with '+25078' or '+25079' followed by 7 digits (e.g., +250781234567).")])),
                ('email', models.EmailField(default='no-email@example.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('emergency_contact_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+2507[89]\\d{7}$', message="Emergency contact number must be a Rwandan number starting with '+25078' or '+25079' followed by 7 digits (e.g., +250781234567).")])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('occupation', models.CharField(default='N/A', max_length=100)),
                ('current_status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('In-transit', 'In-transit'), ('Outpatient', 'Outpatient')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC')], max_length=2)),
                ('image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1/placeholder_image.png', max_length=255, verbose_name='image')),
                ('cloudinary_url', models.URLField(blank=True, null=True)),
                ('current_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facility')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_diagnosis', models.TextField(help_text='Main illness or diagnosis', verbose_name='Primary Diagnosis')),
                ('chronic_condition', models.TextField(blank=True, help_text='Any long-term illnesses (e.g., diabetes, asthma)', verbose_name='Chronic Condition')),
                ('allergies', models.TextField(blank=True, help_text='Known allergies (e.g., penicillin, nuts)', verbose_name='Allergies')),
                ('past_surgeries', models.TextField(blank=True, help_text='Prior surgeries', verbose_name='Past Surgeries')),
                ('current_medication', models.TextField(blank=True, help_text='Current medications', verbose_name='Current Medication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_hospital', models.ForeignKey(limit_choices_to={'is_approved': True}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.facility', verbose_name='Current Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Patient Name')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicalrecord',
            constraint=models.UniqueConstraint(fields=('patient',), name='unique_patient_record'),
        ),
    ]
